name: Release  Package

on:
  push:
    branches:
      - minor
      - patch
jobs:
  package-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Configure git
        run: |
          git config --global user.email github@bhoos.com
          git config --global user.name 'Github Action'
          echo -e "machine github.com\n  login $PERSONAL_ACCESS_TOKEN" >> ~/.netrc
        env:
          PERSONAL_ACCESS_TOKEN: ${{ github.token }}
      - name: Setup package registry access
        uses: ./ # Uses an action in the root directory
      - name: check package
        run: |
          cat package.json
          git branch --show-current

